import classNames from 'classnames';
import Head from 'next/head';

import { FooterFeature } from '../features/footer-feature/footer-feature';
import { HeaderFeature } from '../features/header-feature/header-feature';
import { MainFeature } from '../features/main-feature/main-feature';
export default function Home() {
  const themeClassNames = classNames('dark:bg-gray-500 dark:text-white');
  const headerClassNames = classNames(
    'flex p-3 text-3xl font-bold underline bg-blue-600 text-white',
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={headerClassNames}>
        <HeaderFeature />
      </header>
      <main className={themeClassNames}>
        <MainFeature />
      </main>

      <footer className="flex justify-center">
        <FooterFeature />
      </footer>
    </>
  );
}
