import classNames from 'classnames';
import Head from 'next/head';
import { useSelector } from 'react-redux';

import { FooterFeature } from '../features/footer-feature/footer-feature';
import { MainFeature } from '../features/main-feature/main-feature';
export default function Home() {
  let icon = useSelector((state: { icon: { icon: string } }) => state.icon);

  const moonClassNames = {
    'bg-gray-800 text-slate-50': icon.icon === 'moon',
  };
  const sunClassNames = {
    'bg-slate-50 text-gray-800': icon.icon === 'sun',
  };
  const mainClassNames = classNames(
    'justify-center text-3xl font-bold underline h-screen flex',
    moonClassNames,
    sunClassNames,
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={mainClassNames}>
        <MainFeature />
      </main>
      <footer className="flex justify-center">
        <FooterFeature />
      </footer>
    </>
  );
}
